FROM alpine:3

LABEL author="Grisfian Rusandy"
LABEL company="Mahasiswa Informatika" website="https://www.zenius.net"

RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"

CMD cat "hello/world.txt"
